import type { Metadata } from "next";
import { Inter,Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import NavBar from "@/components/NavBar";


const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
       <body className={inter.className}>
       <NavBar/>
       <h2>testing</h2>
        {children}
        <h2>ototot</h2>
        </body>
       
      </html>
    </ClerkProvider>
  );
}
